config/routes.rb
Rails.application.routes.draw do

  resources :question_and_answers
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"

  resources :groups, param: :token do
    collection do
      post :import
    end
    resources :members, module: :groups, param: :token
  end

  devise_for :users,
  path_names: {},
  controllers: {
    sessions: 'auth/sessions'
  }

  authenticated :user do
    root to: 'groups#index', as: :authenticated_root
  end
  root to: "home#index"

  resources :invitations, only: [:update], module: :home, param: :token do
    member do
      patch :accept
      patch :decline
    end
  end


  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      namespace :groups do
        resources :members, only: [ :index, :update ], param: :token do
          resources :songs, only: [ :create ], module: :members
        end
      end
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/question_and_answer.rb
# == Schema Information
#
# Table name: question_and_answers
#
#  id         :bigint           not null, primary key
#  question   :text
#  answer     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class QuestionAndAnswer < ApplicationRecord

  validates     :question, presence: true
  validates     :answer, presence: true

  default_scope { order(id: :asc) }

end

app/controllers/question_and_answers_controller.rb
class QuestionAndAnswersController < ApplicationController
  before_action :set_question_and_answer, only: [:show, :edit, :update, :destroy]

  # GET /question_and_answers
  # GET /question_and_answers.json
  def index
    @question_and_answers = QuestionAndAnswer.all
  end

  # GET /question_and_answers/1
  # GET /question_and_answers/1.json
  def show
  end

  # GET /question_and_answers/new
  def new
    @question_and_answer = QuestionAndAnswer.new
  end

  # GET /question_and_answers/1/edit
  def edit
  end

  # POST /question_and_answers
  # POST /question_and_answers.json
  def create
    @question_and_answer = QuestionAndAnswer.new(question_and_answer_params)

    respond_to do |format|
      if @question_and_answer.save
        format.html { redirect_to @question_and_answer, notice: 'Question and answer was successfully created.' }
        format.json { render :show, status: :created, location: @question_and_answer }
      else
        format.html { render :new }
        format.json { render json: @question_and_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_and_answers/1
  # PATCH/PUT /question_and_answers/1.json
  def update
    respond_to do |format|
      if @question_and_answer.update(question_and_answer_params)
        format.html { redirect_to @question_and_answer, notice: 'Question and answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_and_answer }
      else
        format.html { render :edit }
        format.json { render json: @question_and_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_and_answers/1
  # DELETE /question_and_answers/1.json
  def destroy
    @question_and_answer.destroy
    respond_to do |format|
      format.html { redirect_to question_and_answers_url, notice: 'Question and answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    skip_before_action :authenticate_user!

    layout 'admin'
    # Use callbacks to share common setup or constraints between actions.
    def set_question_and_answer
      @question_and_answer = QuestionAndAnswer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_and_answer_params
      params.require(:question_and_answer).permit(:question, :answer)
    end
end

app/helpers/question_and_answers_helper.rb
module QuestionAndAnswersHelper
end

app/views/question_and_answers/_form.html.haml
= form_for @question_and_answer do |f|
  - if @question_and_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question_and_answer.errors.count, "error")} prohibited this question_and_answer from being saved:"
      %ul
        - @question_and_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    .block.uppercase.tracking-wide.text-gray-500.text-xs.font-bold.mb-2= f.label :question
    .block.w-full.bg-gray-200.text-gray-800.border.rounded.py-3.px-4.mb-3=f.text_area :question
  .field
    .block.uppercase.tracking-wide.text-gray-500.text-xs.font-bold.mb-2= f.label :answer
    .block.w-full.bg-gray-200.text-gray-800.border.rounded.py-3.px-4.mb-3= f.text_area :answer
  .actions
    = f.submit 'Save', class: "bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded"

app/views/question_and_answers/edit.html.haml
%h1 Editing question_and_answer

= render 'form'

= link_to 'Show', @question_and_answer
\|
= link_to 'Back', question_and_answers_path

app/views/question_and_answers/index.html.haml
%h1 Listing question_and_answers

%table
  %thead
    %tr
      %th Question
      %th Answer
      %th
      %th
      %th

  %tbody
    - @question_and_answers.each do |question_and_answer|
      %tr
        %td= question_and_answer.question
        %td= question_and_answer.answer
        %td= link_to 'Show', question_and_answer
        %td= link_to 'Edit', edit_question_and_answer_path(question_and_answer)
        %td= link_to 'Destroy', question_and_answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question and answer', new_question_and_answer_path

app/views/question_and_answers/new.html.haml
%h1 New question_and_answer

= render 'form'

= link_to 'Back', question_and_answers_path

app/views/question_and_answers/show.html.haml
%p#notice= notice

%p
  %b Question:
  = @question_and_answer.question
%p
  %b Answer:
  = @question_and_answer.answer

= link_to 'Edit', edit_question_and_answer_path(@question_and_answer)
\|
= link_to 'Back', question_and_answers_path