config/routes.rb
Rails.application.routes.draw do

  resources :question_and_answers
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"

  resources :groups, param: :token do
    collection do
      post :import
    end
    resources :members, module: :groups, param: :token
  end

  devise_for :users,
  path_names: {},
  controllers: {
    sessions: 'auth/sessions'
  }

  authenticated :user do
    root to: 'groups#index', as: :authenticated_root
  end
  root to: "home#index"

  resources :invitations, only: [:update], module: :home, param: :token do
    member do
      patch :accept
      patch :decline
    end
  end


  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      namespace :groups do
        resources :members, only: [ :index, :update ], param: :token do
          resources :songs, only: [ :create ], module: :members
        end
      end
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/home/invitations_controller.rb
class Home::InvitationsController < ApplicationController

  def update
    @group_member = Group::Member.find_by!(token: url_params[:token])
    respond_to do |format|
      if @group_member.update(data_params)
        format.js
      else
        format.json { render json: @group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  def accept
    @group_member = Group::Member.find_by!(token: url_params[:token])
    # ::ResponseCaptureWorker.perform_async( @group_member.token, 'accept' )
    respond_to do |format|
      if @group_member.confirm_rsvp!
        format.js
      else
        format.json { render json: @group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  def decline
    @group_member = Group::Member.find_by!(token: url_params[:token])
    # ::ResponseCaptureWorker.perform_async( @group_member.token, 'decline' )
    respond_to do |format|
      if @group_member.decline_invitation!
        format.js
      else
        format.json { render json: @group_member.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  skip_before_action :authenticate_user!

  def url_params
    params.permit(
      :token
    )
  end

  def data_params
    params.require(:group_member).permit(
      :dietary_preference
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # group = Group.eager_load(:members).find_by!(token: url_params[:gt])
    @group = Group.eager_load(:members).eager_load(:song_requests).find_by!(token: url_params[:gt])
    @current_member = Group::Member.find_by!(token: url_params[:token])
    @questions = QuestionAndAnswer.all
  end

  def accept
    group_member = Group::Member.find_by!(token: url_params[:token])
    group_member.confirm_rsvp!
  end

  def decline

  end

  private

  layout 'public'

  skip_before_action :authenticate_user!

  def url_params
    params.permit(
      :gt, # Group Token
      :token # Group Member Token
    )
  end

  def song_request_params
    params.require(:song_request).permit(
      :name,
      :artist
    )
  end
end

app/views/home/invitations/_invitation_actions.haml
- if member.not_yet_responded?
  .flex.flex-col
    = link_to "Accept Invitation", accept_invitation_path(member.token), method: :patch, remote: true, class: "border border-green-200 hover:bg-green-300 text-green-500 hover:text-green-600 font-bold my-2 py-2 px-4 rounded w-full text-center", data: { disable_with: "Accepting..."}
    = link_to "Decline Invitation", decline_invitation_path(member.token), method: :patch, remote: true, class: "border border-red-200 hover:bg-red-300 text-red-500 hover:text-red-600 font-bold my-2 py-2 px-4 rounded w-full text-center", data: { disable_with: "Declining..."}
- elsif member.has_declined?
  .w-full.flex
    %span.text-base.w-full.text-center.font-medium.bg-red-100.py-1.px-2.rounded.text-red-500.align-middle Sorry that you could not join us
- elsif member.has_confirmed?
  .w-full.flex.flex-col
    %span.text-base.w-full.text-center.font-medium.bg-green-100.py-1.px-2.rounded.text-green-500.align-middle Thank you for accepting your invitation

    - if member.dietary_preference.blank?
      .py-2.expanda{ data: { controller: 'expanda '}}
        .w-full.text-center.mt-3
          = link_to "Any dietary preferences?", "#", class: "ghost-button" , data: { target: "expanda.openEl", action: "click->expanda#toggle" }
        .w-full.text-right
          = link_to "X", "#" , data: { target: "expanda.closeEl", action: "click->expanda#toggle" }, class: "hidden ghost-button"
        .expanda--panel{ data: { target: "expanda.panel"}}
          = form_with model: member, url: invitation_path(member.token), method: :patch, remote: true do |f|
            .my-2
              = f.text_area :dietary_preference, placeholder: "Tell us if you are Vegan, Vegatarian or have any food allergies...",class: "w-full bg-gray-100 rounded p-4 resize-none"
            .my-2.flex.w-full.justify-end
              = f.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer", data: { disable_with: "Saving..."}
    - else
      .py-4.w-full.mt-3
        %h5.text-sm.font-semibold.text-gray-500="Dietary Preferences"
        %p.text-sm= member.dietary_preference

app/views/home/invitations/accept.js.erb
var el = document.createElement('div');
el.style.cssText = 'display:hidden;';

<% if @group_member.persisted? %>
  document.getElementById("invitation-actions-<%= @group_member.token %>").innerHTML = "<%= j render(partial: 'invitation_actions', locals: { member: @group_member }) %>";
  el.setAttribute('data-notyf-type', 'success');
  el.setAttribute('data-notyf-message', "Awesome! Can't wait to see you at the wedding");
<% else %>
  el.setAttribute('data-notyf-type', 'error');
  el.setAttribute('data-notyf-message', "Something went wrong. Please try again later...or phone Samantha");
<% end %>


el.setAttribute('data-controller', 'notyf');
document.body.appendChild(el);

app/views/home/invitations/decline.js.erb
var el = document.createElement('div');
el.style.cssText = 'display:hidden;';

<% if @group_member.persisted? %>
  document.getElementById("invitation-actions-<%= @group_member.token %>").innerHTML = "<%= j render(partial: 'invitation_actions', locals: { member: @group_member }) %>";
  el.setAttribute('data-notyf-type', 'success');
  el.setAttribute('data-notyf-message', "It's a pity you can't join us.");
<% else %>
  el.setAttribute('data-notyf-type', 'error');
  el.setAttribute('data-notyf-message', "Something went wrong. Please try again later...or phone Samantha");
<% end %>


el.setAttribute('data-controller', 'notyf');
document.body.appendChild(el);

app/views/home/invitations/update.js.erb
var el = document.createElement('div');
el.style.cssText = 'display:hidden;';

<% if @group_member.persisted? %>
  document.getElementById("invitation-actions-<%= @group_member.token %>").innerHTML = "<%= j render(partial: 'invitation_actions', locals: { member: @group_member }) %>";
  el.setAttribute('data-notyf-type', 'success');
  el.setAttribute('data-notyf-message', "Your preferences have been updated");
<% else %>
  el.setAttribute('data-notyf-type', 'error');
  el.setAttribute('data-notyf-message', "Something went wrong. Please try again later...or phone Samantha");
<% end %>


el.setAttribute('data-controller', 'notyf');
document.body.appendChild(el);